# Generated by Django 4.1.5 on 2023-01-18 12:54

from django.db import migrations, models
import mysite.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivroVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('comentario', models.CharField(max_length=400, verbose_name='Comentário')),
                ('recomenda', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=mysite.models.get_file_patch, variations={'thumb': {'crop': True, 'height': 480, 'widht': 480}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
