# Generated by Django 4.1.5 on 2023-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrovisitas',
            name='recomenda',
            field=models.BooleanField(default=False, verbose_name='Recomendaria o site?'),
        ),
    ]
