# Generated by Django 4.1.5 on 2023-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_livrovisitas_recomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Nome'),
        ),
    ]
