# Generated by Django 4.1.5 on 2023-01-18 13:10

from django.db import migrations
import mysite.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to=mysite.models.get_file_patch, variations={'thumb': {'crop': True, 'height': 480, 'widht': 480}}, verbose_name='Foto'),
        ),
    ]
