# Generated by Django 4.1.5 on 2023-01-18 19:34

from django.db import migrations, models
import mysite.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrovisitas',
            name='comentario',
            field=models.TextField(max_length=400, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=mysite.models.get_file_patch, variations={'thumb': {'crop': True, 'height': 480, 'widht': 480}}, verbose_name='Foto'),
        ),
    ]
