# Generated by Django 4.1.5 on 2023-01-18 19:43

from django.db import migrations, models
import mysite.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_livrovisitas_comentario_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=mysite.models.get_file_patch, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
