# Generated by Django 4.1.5 on 2023-01-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_livrovisitas_recomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrovisitas',
            name='recomenda',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=6, verbose_name='Você recomenda o autor desta página?'),
        ),
    ]
