# Generated by Django 4.1.5 on 2023-01-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_livrovisitas_recomenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrovisitas',
            name='recomenda',
        ),
    ]
