# Generated by Django 4.1.5 on 2023-01-24 14:57

from django.db import migrations, models
import mysite.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_livrovisitas_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=115, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=mysite.models.get_file_patch, variations={}, verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
