# Generated by Django 4.1.5 on 2023-01-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Link'),
        ),
    ]
